### ISSUE TITLE
Redesign the package

### ISSUE THREAD

**Issue by PrzeChoj** [PrzeChoj/gips#11]
The design and names used in the package have to be changed slightly.

- [x] Introducing the `gips()` function that will be the wrapper for optimization algorithms looking for the permutation. There are now two algorithms, the Metropolis-Hastings and the best growth, but we plan to introduce the simulated annealing and the evolutionary algorithm in the future
- [x] `MH()` function will have changed the name to sth more meaningful
- [x] It is the same for `goal_function()`, especially since now it is logarithm-based
- [x] The terms of the attributes have to be thought through: `n_number`, `max_iter` (it is precisely the number of iterations for `MH`, but will be the maximum number of iterations for simulated annealing and the evolutionary algorithm in the future)
- [x] The `U` parameter from $U={\sum_{i=1}}^n(Z_i\cdot Z_i^T)$ has to be changed into the `S` parameter $S=\frac{U}{n}$

**Comment by PrzeChoj** [comment]
It would also be good to later do some restyling:

- [x] Restyle the code for example using [styler](https://styler.r-lib.org) package
- [x] Write readable documentation
- [ ] Make `gips` logo?
- [x] Build website with [pkgdown](https://pkgdown.r-lib.org/)

**Comment by PrzeChoj** [comment]
The redesign has started on the `redesign` branch.

1. The function rename: `MH()` --->>> `Metropolis_Hastings()`.
2. The argument rename: `n_number` --->>> `number_of_observations`.
3. The function rename: `goal_function()` --->>> `log_likelihood_of_perm()`.
4. The things in list of `gips` class rename:
 - `goal_function_logvalues` --->>> `log_likelihood_values`
 - `found_point_function_logvalue` --->>> `found_perm_log_likelihood`
 - `last_point_function_logvalue` --->>> `last_perm_log_likelihood`
 - `goal_function_best_logvalues` --->>> `[deleted]`
 - `points` --->>> `visited_perms`
 - `found_point` --->>> `found_perm`
 - `last_point` --->>> `last_perm`
5. Argument rename: `estimate_probabilities(points)` --->>> `estimate_probabilities(perms)`

**Comment by PrzeChoj** [comment]
When one has to estimate the mean, I'm not sure what the user should do...

**Comment by PrzeChoj** [comment]
In some places we use `if(...) {rlang::abort(...)}` in others we use `stopifnot(...)`. I think we should decide which one to use.

**Comment by PrzeChoj** [comment]
Right now, the `gips` workflow is like this: One calls the `gips()` function with all the nasty parameters and then waits a long time to get the result.

I think this is an excellent place to use the Builder design pattern:
1. Function `x <- gips(S, delta, D_matrix)`
2. Function `optimize.gips(x, ...)` with an additional parameter such as the optimizer and the parameters of it
3. Function `continue.gips(x, num_of_iters)` that remembers the list optimization process and runs it for a longer time

Edit: The `gips()` function will also have `number_of_observations` as a parameter. `gips(S, number_of_observations, delta, D_matrix)`.

**Comment by PrzeChoj** [comment]
Additionally, I think a good idea would be to add the user option to choose whether he wants to set the maximum number of iterations or the optimisation time.

Edit: I made a separate ISSUE for this: #13

**Comment by PrzeChoj** [comment]
I'm unsure how to reference the value of a `log_likelihood_of_perm()` function. It is not likelihood, but sth proportional to it. The same problem arises in `plot.gips()`, `print.gips()`.

**Comment by MrDomani** [comment]
> When one has to estimate the mean, I'm not sure what the user should do...

Not our problem. The paper starts with assumption mean=0 and our main goal is to implement the ideas presented in the paper. 
We could ask supervisor about it.

> In some places we use `if(...) {rlang::abort(...)}` in others we use `stopifnot(...)`. I think we should decide which one to use.

I'm an advocate of `rlang::abort`, because it allows user to show traceback and rerun with debug. It is also [recommended](https://style.tidyverse.org/error-messages.html) by Hadley.

> Right now, the `gips` workflow is like this: One calls the `gips()` function with all the nasty parameters and then waits a long time to get the result.
> 
> I think this is an excellent place to use the Builder design pattern:
> 
> 1. Function `x <- gips(S, delta, D_matrix)`
> 2. Function `optimize.gips(x, ...)` with an additional parameter such as the optimizer and the parameters of it
> 3. Function `continue.gips(x, num_of_iters)` that remembers the list optimization process and runs it for a longer time

Kinda like sklearnish init - fit - predict. I like it.

> I'm unsure how to reference the value of a `log_likelihood_of_perm()` function. It is not likelihood, but sth proportional to it. The same problem arises in `plot.gips()`, `print.gips()`.

Well, likelihood does not have to be normalized over domain of interest. We can define the likelihood as unnormalized posterior probability. Its intuitive. Certainly more intuitive than strict mathematical *unnormalised probability* AKA *measure*.

**Comment by PrzeChoj** [comment]
> Well, likelihood does not have to be normalized over domain of interest.

I think it does. [Wikipedia](https://en.wikipedia.org/wiki/Likelihood_function) sais $\mathcal{L}(\theta | x) = P_\theta (x)$, but we have $f(\theta | x) \propto P_\theta (x)$.

**Comment by PrzeChoj** [comment]
> I'm an advocate of rlang::abort, because it allows user to show traceback and rerun with debug. It is also [recommended](https://style.tidyverse.org/error-messages.html) by Hadley.

Done

**Comment by PrzeChoj** [comment]
To wrap things up.
The list of things that are left to do to complete the redesigning:
- [x] Redesign the optimizing with the Builder design pattern;
- [x] Reexamine `plot.gips()`, `print.gips()`. Write `summary.gips()` and `str.gips()` (UPDATE: we abandoned the idea of `str.gips()`);
- [x] Write the `continue.gips()` function, or adjust the `find_gips()`. See: #18 ;
- [x] Reference clearly that `exp(log_likelihood_of_perm(...))` is only proportional to likelihood. Done in #20.
- [x] Documentation.

**Comment by PrzeChoj** [comment]
I believe the corpus of the redesign is ready. This is why I deleted the "redesign" branch. The rest of the changes will be processed as always.

**Comment by PrzeChoj** [comment]
The documentation is ready.

And so, the last* thing listed here is ready, so I can finally close this issue.

Phew, what a journey!
