### ISSUE TITLE
`heatmap` of gips object

### ISSUE THREAD

**Issue by PrzeChoj** [PrzeChoj/gips#15]
I thought it would be nice to be able to call just `heatmap(g)`, where `g` is of `gips` class. It would be implemented like `heatmap(gips::project_matrix(attr(g, "S"), g[[1]]), Rowv = NA, Colv = NA)`.

Is it a good idea? Can it be useful?

The minor technical issue is that `stats::heatmap` is not a generic function. We have two options now: make it generic in our package and set the `heatmap.default` to `stats::heatmap`; or call this function sth like `heatmap_gips(g)`.

What do you think, @MrDomani ?

**Comment by MrDomani** [comment]
I agree, that having a convenient way to plot such heatmap would be nice. Since it looks like it needs little, but not obvious code, adding such wrapper is a good idea. 
Maybe instead of overriding `heatmap`, we could add another option for `type` parameter in `plot.gips`?

**Comment by PrzeChoj** [comment]
Good idea with this `type`.
Another way can be as in `plot(lm(a~., data.frame(a=1:3, b=3:5)))`, where `R` asks: "Press Enter for the next plot".

**Comment by PrzeChoj** [comment]
I decided to add this as @MrDomani  proposed.
There will be `type = 'heatmap'` in `plot.gips()`. I will change the default `type` from `type = 'both'` to `type = NA`, which will be automagically changed to `'heatmap'` for non-optimized `gips` objects, and to `'both'` for optimized ones.
Using the `type = NA` will produce a warning.

**Comment by PrzeChoj** [comment]
The `stats::heatmap()` function does not met our expectations. We will use the `ggplot2::geom_raster()` function.

**Comment by PrzeChoj** [comment]
Done in 17323c84f1f7df859838d03dd243208a1b14291a
