### ISSUE TITLE
`return_probabilities=TRUE`does not work with rlang < 0.4.10

### ISSUE THREAD

**Issue by MrDomani** [PrzeChoj/gips#30]
In non-interactive sessions, one should use `is_installed` instead. 
We have `check_installed` in 2 places: for `return_probabilities=TRUE` and for `plot.gips`.
Both could be used in non-interactive sessions, the first one surely.

**Comment by MrDomani** [comment]
Huh, an R session started with `R`from console is an interactive session.

**Comment by MrDomani** [comment]
Oh, now I see. The machine, that I am running code on, has rlang package version 0.4.4. check_installed was introduced in 0.4.10 .

**Comment by PrzeChoj** [comment]
I added an appropriate note in description ~6c26ebd8af6dc43ba56033383c3f30c366f6f724~ b2caf2d63f2584de974d1e0c8234c18a5f2d2575
